gpio export 21 out
gpio export 16 out
gpio export 13 out
gpio export 11 out
gpio export 5 out
gpio export 26 out
gpio export 19 out
gpio export 20 out
gpio export 6 out
gpio export 12 out
gpio export 7 out
gpio export 8 out
